# Generated by Django 2.1.3 on 2018-11-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skarbnik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
