# Generated by Django 2.0.2 on 2019-01-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skarbnik', '0001_initial'),
    ]

    operations = [
       
    ]
