# Generated by Django 2.1.3 on 2018-11-24 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skarbnik', '0002_auto_20181124_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='class_field',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='skarbnik.Class'),
        ),
    ]
