# Generated by Django 2.1.3 on 2018-11-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skarbnik', '0002_auto_20181125_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
