# Generated by Django 2.0.2 on 2019-01-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skarbnik', '0002_remove_payment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
