# Generated by Django 2.1.3 on 2018-11-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skarbnik', '0003_auto_20181125_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
