# Generated by Django 2.1.3 on 2018-11-24 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skarbnik', '0003_auto_20181124_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skarbnik.Payment'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skarbnik.Student', unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_field',
            field=models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='skarbnik.Class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
