# Generated by Django 2.0.2 on 2019-01-26 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skarbnik', '0003_payment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
