# Generated by Django 2.0.2 on 2019-02-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skarbnik', '0004_paymentdetail_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='PLN', max_length=10),
        ),
    ]
