# Generated by Django 2.0.2 on 2019-03-09 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skarbnik', '0005_payment_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='image',
        ),
        migrations.AddField(
            model_name='paymentimage',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='skarbnik.Payment'),
        ),
    ]
