# Generated by Django 2.1.3 on 2018-11-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skarbnik', '0005_auto_20181124_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_field',
            field=models.AutoField(db_column='id_', primary_key=True, serialize=False),
        ),
    ]
