# Generated by Django 2.0.2 on 2019-03-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skarbnik', '0006_auto_20190309_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentimage',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
