# Generated by Django 2.1.3 on 2018-11-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skarbnik', '0006_auto_20181125_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='creation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='start_date',
            field=models.DateField(),
        ),
    ]
