# Generated by Django 2.1.3 on 2018-11-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skarbnik', '0009_auto_20181125_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
