# Generated by Django 2.1.3 on 2018-11-25 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skarbnik', '0010_auto_20181125_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skarbnik.Student'),
        ),
    ]
